import {ETFMarketData,calculateOpportunityScore,Candle} from "@/lib/engine";
export type AdvancedETF=ETFMarketData&{ma20?:number;ma50?:number;ma200?:number;relativeStrength1yPct?:number;trendConsistencyPct?:number;scoreChange1d?:number;confidence?:"HIGH"|"MEDIUM"|"LOW";referenceLow?:number;referenceHigh?:number};
export type Backtest={periodDays:number;strategyReturnPct:number;benchmarkReturnPct:number;excessReturnPct:number;maxDrawdownPct:number;strategyCagrPct:number;benchmarkCagrPct:number;winRatePct:number;rebalances:number;method:string};
const r=(v:number|undefined)=>v===undefined||!Number.isFinite(v)?undefined:Math.round(v*100)/100;
const sma=(c:Candle[],n:number)=>c.length<n?undefined:c.slice(-n).reduce((s,x)=>s+x[4],0)/n;
const vol=(c:Candle[])=>{const p=c.slice(-21).map(x=>x[4]),z:number[]=[];for(let i=1;i<p.length;i++)if(p[i-1]>0)z.push(p[i]/p[i-1]-1);if(z.length<2)return 0;const m=z.reduce((a,b)=>a+b,0)/z.length;return Math.sqrt(z.reduce((a,b)=>a+(b-m)**2,0)/(z.length-1))*Math.sqrt(252)*100};
const scoreAt=(c:Candle[],i:number)=>{if(i<252)return undefined;const close=(n:number)=>c[i-n]?.[4],cur=c[i][4],high=Math.max(...c.slice(i-251,i+1).map(x=>x[2]));const p=(a:number|undefined,b:number)=>a===undefined?0:(b/a-1)*100;return calculateOpportunityScore({return20dPct:p(close(20),cur),return90dPct:p(close(90),cur),return1yPct:p(close(252),cur),drawdownPct:(cur/high-1)*100,volatility20dPct:vol(c.slice(0,i+1))})};
export function enrich(items:ETFMarketData[]):AdvancedETF[]{const b=items.find(x=>x.symbol==="NIFTYBEES");return items.map(x=>{if(x.signal==="DATA ERROR"||!x.candles)return x;const c=[...x.candles].sort((a,b)=>a[0].localeCompare(b[0])),current=x.price??c[c.length-1]?.[4],ma20=sma(c,20),ma50=sma(c,50),ma200=sma(c,200),rs=b?.return1yPct!==undefined&&x.return1yPct!==undefined?x.return1yPct-b.return1yPct:undefined,prev=c.length>=254?scoreAt(c,c.length-2):undefined,referenceLow=ma50!==undefined&&current!==undefined?Math.min(current,Math.max(ma50,current*0.92)):undefined,referenceHigh=ma20!==undefined&&current!==undefined?Math.max(current,ma20):current,cons=c.slice(-100),up=cons.slice(1).filter((_,i)=>cons[i+1][4]>=cons[i][4]).length,consistency=cons.length>1?up/(cons.length-1)*100:undefined,agreement=[(x.return20dPct??0)>0,(x.return90dPct??0)>0,(x.return1yPct??0)>0,(rs??0)>0,(x.drawdownPct??0)>-30].filter(Boolean).length,confidence=x.score!==undefined&&x.score>=75&&agreement>=4?"HIGH":x.score!==undefined&&x.score>=60&&agreement>=3?"MEDIUM":"LOW";return{...x,ma20:r(ma20),ma50:r(ma50),ma200:r(ma200),relativeStrength1yPct:r(rs),scoreChange1d:prev===undefined?undefined:r((x.score??0)-prev),trendConsistencyPct:r(consistency),confidence,referenceLow:r(referenceLow),referenceHigh:r(referenceHigh)}})}
export function buildBacktest(items:AdvancedETF[]):Backtest|undefined{const valid=items.filter(x=>x.candles&&x.candles.length>=253);if(valid.length<3)return undefined;const bench=valid.find(x=>x.symbol==="NIFTYBEES")??valid[0],dates=bench.candles!.map(x=>x[0]).sort(),start=253,HOLD=20;let equity=1,b=1,peak=1,maxDd=0,wins=0,trades=0;for(let i=start;i+HOLD<dates.length;i+=HOLD){const d=dates[i],ranked=valid.map(e=>{const c=e.candles!,idx=c.findIndex(x=>x[0]===d);return{e,idx,s:idx>=252?scoreAt(c,idx):undefined}}).filter(x=>x.s!==undefined).sort((a,b)=>(b.s!)-(a.s!));if(!ranked.length)continue;const endDate=dates[i+HOLD],pick=ranked[0],pc=pick.e.candles!,ei=pc.findIndex(x=>x[0]===endDate),bi=bench.candles!.findIndex(x=>x[0]===endDate);if(ei<=pick.idx||bi<=i)continue;const ret=pc[ei][4]/pc[pick.idx][4]-1;equity*=1+ret;b*=bench.candles![bi][4]/bench.candles![i][4];trades++;if(ret>0)wins++;peak=Math.max(peak,equity);maxDd=Math.min(maxDd,(equity/peak-1)*100)}const days=dates.length-start,years=days/252;if(years<1||trades<5)return undefined;return{periodDays:days,strategyReturnPct:r((equity-1)*100)!,benchmarkReturnPct:r((b-1)*100)!,excessReturnPct:r((equity-b)*100)!,maxDrawdownPct:r(maxDd)!,strategyCagrPct:r((Math.pow(equity,1/years)-1)*100)!,benchmarkCagrPct:r((Math.pow(b,1/years)-1)*100)!,winRatePct:r(wins/trades*100)!,rebalances:trades,method:"Top-score rotation every 20 trading days over the full available 5-year daily history after a 252-trading-day warm-up. Each historical score uses only information available on that date; CAGR is annualized only when at least one full year is tested. Historical simulation only, before taxes and execution costs; no guarantee of future returns."}}
export function dailyBrief(items:AdvancedETF[]){const valid=items.filter(x=>x.score!==undefined),sorted=[...valid].sort((a,b)=>(b.score??-1)-(a.score??-1)),top=sorted.slice(0,3),acc=valid.filter(x=>x.signal==="ACCUMULATE").length,bull=valid.filter(x=>(x.return1yPct??0)>0).length;return{top,accumulateCount:acc,breadthPct:valid.length?bull/valid.length*100:0,avg1yPct:valid.length?valid.reduce((s,x)=>s+(x.return1yPct??0),0)/valid.length:0}}
