export type Signal="ACCUMULATE"|"HOLD"|"WATCH"|"DATA ERROR";
export type Candle=[string,number,number,number,number,number,number];
export type ETFDefinition={symbol:string;name:string;exposure:string;role:string};
export type ETFMarketData=ETFDefinition&{instrumentKey?:string;price?:number;previousClose?:number;dayChangePct?:number;return5dPct?:number;return20dPct?:number;return90dPct?:number;return1yPct?:number;high52Week?:number;drawdownPct?:number;volatility20dPct?:number;score?:number;signal:Signal;reason?:string;error?:string;candles?:Candle[]};
export const ETF_UNIVERSE:ETFDefinition[]=[{symbol:"NIFTYBEES",name:"Nifty 50",exposure:"Nifty 50",role:"Core"},{symbol:"GOLDBEES",name:"Gold",exposure:"Gold",role:"Diversifier"},{symbol:"SILVERBEES",name:"Silver",exposure:"Silver",role:"Commodity"},{symbol:"JUNIORBEES",name:"Nifty Next 50",exposure:"Nifty Next 50",role:"Growth"},{symbol:"MID150BEES",name:"Nifty Midcap 150",exposure:"Nifty Midcap 150",role:"Growth"},{symbol:"MON100",name:"Nasdaq 100",exposure:"Nasdaq 100",role:"Global Growth"},{symbol:"BANKBEES",name:"Nifty Bank",exposure:"Nifty Bank",role:"Financials"},{symbol:"ITBEES",name:"Nifty IT",exposure:"Nifty IT",role:"Technology"},{symbol:"PHARMABEES",name:"Nifty Pharma",exposure:"Nifty Pharma",role:"Defensive"},{symbol:"CPSEETF",name:"CPSE",exposure:"CPSE",role:"PSU / Value"}];
type Search={status:string;data?:Array<{instrument_key:string;trading_symbol?:string;segment?:string;instrument_type?:string;exchange?:string}>};type Quote={last_price:number;instrument_token:string;cp:number};type Ltp={status:string;data?:Record<string,Quote>};type Hist={status:string;data?:{candles?:Candle[]}};const BASE="https://api.upstox.com";
function headers(token:string){return{Accept:"application/json","Content-Type":"application/json",Authorization:`Bearer ${token}`}}function record(v:unknown):v is Record<string,unknown>{return typeof v==="object"&&v!==null}
async function upstox<T>(url:string,token:string,revalidate=0):Promise<T>{const r=await fetch(url,{headers:headers(token),...(revalidate?{next:{revalidate}}:{cache:"no-store"})});const b:unknown=await r.json().catch(()=>({}));if(!r.ok){const es=record(b)?b.errors:undefined;const e=Array.isArray(es)&&record(es[0])?es[0]:undefined;throw new Error(typeof e?.message==="string"?e.message:`Upstox HTTP ${r.status}`)}return b as T}
export async function resolveInstrument(symbol:string,token:string){const p=new URLSearchParams({query:symbol,exchanges:"NSE",segments:"EQ",instrument_types:"EQ",page_number:"1",records:"30"});const r=await upstox<Search>(`${BASE}/v2/instruments/search?${p.toString()}`,token,86400);const rows=r.data??[];const exact=rows.find(x=>x.trading_symbol?.toUpperCase()===symbol.toUpperCase()&&x.segment==="NSE_EQ"&&x.instrument_type==="EQ");const fallback=rows.find(x=>x.trading_symbol?.toUpperCase()===symbol.toUpperCase()&&x.segment==="NSE_EQ");const c=exact??fallback;if(!c?.instrument_key)throw new Error(`Instrument not found for ${symbol}; Upstox returned ${rows.length} matches`);return c.instrument_key}
export function percentageReturn(from:number|undefined,to:number|undefined){if(from===undefined||to===undefined||from===0)return undefined;return(to/from-1)*100}
export function calculate52WeekHigh(candles:Candle[]){const ordered=[...candles].sort((a,b)=>a[0].localeCompare(b[0])).slice(-252);return ordered.length?Math.max(...ordered.map(c=>c[2])):undefined}
export function calculateDrawdown(current:number,high52Week:number){return(current/high52Week-1)*100}
export function annualizedVolatility(candles:Candle[]){const o=[...candles].sort((a,b)=>a[0].localeCompare(b[0])).slice(-21),r:number[]=[];for(let i=1;i<o.length;i++){const p=o[i-1][4];if(p>0)r.push(o[i][4]/p-1)}if(r.length<2)return 0;const m=r.reduce((s,v)=>s+v,0)/r.length;const variance=r.reduce((s,v)=>s+(v-m)**2,0)/(r.length-1);return Math.sqrt(variance)*Math.sqrt(252)*100}
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
export function calculateOpportunityScore(x:{return20dPct:number;return90dPct:number;return1yPct:number;drawdownPct:number;volatility20dPct:number}){const oneYear=clamp(50+x.return1yPct,0,100),ninety=clamp(50+x.return90dPct*1.5,0,100),medium=clamp(50+x.return20dPct*2,0,100);const trend=oneYear*.4+ninety*.25+medium*.15;const dd=x.drawdownPct>=-10?70:x.drawdownPct>=-20?90:x.drawdownPct>=-30?100:45;const risk=clamp(100-Math.max(0,x.volatility20dPct-15)*1.5,20,100);return Math.round(clamp(trend+dd*.12+risk*.08,0,100))}
export function classifySignal(score:number,r20:number,r90:number,r1y:number,dd:number):Signal{const longTrend=r1y>0&&r90>0,healthyPullback=dd<=-5&&dd>-30;if(score>=70&&longTrend&&healthyPullback)return"ACCUMULATE";if(score>=55&&longTrend)return"HOLD";return"WATCH"}
export function explainSignal(signal:Signal,r20:number,r90:number,r1y:number,dd:number){if(signal==="ACCUMULATE")return`Long-term trend is positive across 1Y and 90D, with a ${Math.abs(dd).toFixed(2)}% pullback from the 52-week high creating a potentially attractive long-term entry zone.`;if(signal==="HOLD")return"Long-term trend remains constructive, but the current price is not in a strong accumulation zone.";if(signal==="DATA ERROR")return"Market data is unavailable or insufficient for a reliable long-term signal.";if(r1y<=0)return"1Y trend is not positive, so the engine is avoiding a high-conviction long-term accumulation signal.";if(r90<=0)return"90D trend is not yet positive enough to confirm the long-term trend.";if(dd<=-30)return"The ETF is more than 30% below its 52-week high, so the long-term risk profile requires caution.";return"The long-term trend and entry conditions are not strong enough for a high-conviction accumulation signal."}
export function marketRegime(items:ETFMarketData[]):"BULLISH"|"BALANCED"|"DEFENSIVE"{const v=items.filter(x=>x.return1yPct!==undefined);if(!v.length)return"BALANCED";const avg=v.reduce((s,x)=>s+(x.return1yPct??0),0)/v.length,share=v.filter(x=>(x.return1yPct??0)>0).length/v.length;if(avg>=10&&share>=.6)return"BULLISH";if(avg<=-10&&share<=.4)return"DEFENSIVE";return"BALANCED"}
const round=(v:number|undefined)=>v===undefined||!Number.isFinite(v)?undefined:Math.round(v*100)/100;
export async function getETFMarketData():Promise<ETFMarketData[]>{const token=process.env.UPSTOX_ANALYTICS_TOKEN?.trim();if(!token)throw new Error("UPSTOX_ANALYTICS_TOKEN is not configured");const resolved=await Promise.all(ETF_UNIVERSE.map(async etf=>{try{return{etf,instrumentKey:await resolveInstrument(etf.symbol,token),error:undefined as string|undefined}}catch(error){return{etf,instrumentKey:undefined,error:error instanceof Error?error.message:"Instrument lookup failed"}}}));const keys=resolved.filter((x):x is{etf:ETFDefinition;instrumentKey:string;error:undefined}=>Boolean(x.instrumentKey));let quotes=new Map<string,Quote>();try{if(keys.length){const p=new URLSearchParams({instrument_key:keys.map(x=>x.instrumentKey).join(",")});const r=await upstox<Ltp>(`${BASE}/v3/market-quote/ltp?${p.toString()}`,token);for(const [responseKey,q] of Object.entries(r.data??{})){const normalized=responseKey.replace(":","|");quotes.set(normalized,q);if(q.instrument_token)quotes.set(q.instrument_token,q)}}}catch(error){const msg=error instanceof Error?error.message:"LTP request failed";quotes=new Map();for(const item of resolved)if(item.instrumentKey)item.error=msg}
const now=new Date(),to=now.toISOString().slice(0,10),d=new Date(now);d.setDate(d.getDate()-400);const from=d.toISOString().slice(0,10);const historical=await Promise.all(keys.map(async({etf,instrumentKey})=>{try{const r=await upstox<Hist>(`${BASE}/v3/historical-candle/${encodeURIComponent(instrumentKey)}/days/1/${to}/${from}`,token,21600);return{symbol:etf.symbol,candles:r.data?.candles??[],error:undefined as string|undefined}}catch(error){return{symbol:etf.symbol,candles:[],error:error instanceof Error?error.message:"Historical data failed"}}}));const bySymbol=new Map(historical.map(x=>[x.symbol,x]));return resolved.map(({etf,instrumentKey,error})=>{if(!instrumentKey||error)return{...etf,signal:"DATA ERROR" as const,error:error??"Instrument unavailable"};const quote=quotes.get(instrumentKey),hist=bySymbol.get(etf.symbol),history=hist?.candles??[];if(!quote||history.length<253)return{...etf,instrumentKey,signal:"DATA ERROR" as const,error:!quote?"Live quote unavailable":hist?.error??`Insufficient historical data (${history.length} candles; 253 required)`};const ordered=[...history].sort((a,b)=>a[0].localeCompare(b[0])),at=(n:number)=>ordered[ordered.length-1-n]?.[4],current=quote.last_price,high=calculate52WeekHigh(ordered);if(high===undefined)return{...etf,instrumentKey,signal:"DATA ERROR" as const,error:"52-week high unavailable"};const day=percentageReturn(quote.cp,current)??0,r5=percentageReturn(at(5),current)??0,r20=percentageReturn(at(20),current)??0,r90=percentageReturn(at(90),current)??0,r1y=percentageReturn(at(252),current)??0,dd=calculateDrawdown(current,high),vol=annualizedVolatility(ordered),score=calculateOpportunityScore({return20dPct:r20,return90dPct:r90,return1yPct:r1y,drawdownPct:dd,volatility20dPct:vol}),signal=classifySignal(score,r20,r90,r1y,dd);return{...etf,instrumentKey,price:round(current),previousClose:round(quote.cp),dayChangePct:round(day),return5dPct:round(r5),return20dPct:round(r20),return90dPct:round(r90),return1yPct:round(r1y),high52Week:round(high),drawdownPct:round(dd),volatility20dPct:round(vol),score,signal,reason:explainSignal(signal,r20,r90,r1y,dd),candles:ordered}})}